### ISSUE TITLE
color issue with scribl.min.js

### ISSUE THREAD

**Issue by ghost** [chmille4/Scribl#11]
Glyph color is black by default, 
hover the mouse on the canvas to reset color to what is specified in the code

**Comment by chmille4** [comment]
george

I'm having trouble recreating this.  Can you provide a test case?

**Comment by chmille4** [comment]
I'm not sure if you get a notification when I comment on the issue you
opened so I'll just send you an email as well.

I'm having trouble reproducing the bug you describe.  Can you send me some
code that displays this issue?

Thanks,
Chase

**Comment by ghost** [comment]
Sent example code via email.

**Comment by ghost** [comment]
Hi Chase,
I have attached 2 images of the rendered gylphs from the same code. Before
hovering the mouse and after hovering the mouse

Thanks
George

On Thu, Apr 7, 2011 at 8:43 PM, George Githinji georgkam@gmail.com wrote:

> Hi  Chase,
> Am using Rails3 and erb template to generate the resulting javascript. So
> when i load the page, the glyph name is in black, and the text font is about
> 12. Upon hovering the mouse on the canvas object. The correct textcolor
> (white) as specified in the code.
> 
>  function draw(canvasName) {
> // Get Canvas and Create Chart
> canvas = document.getElementById(canvasName);
> 
>  // create a canvas chart
> chart = new Scribl(canvas, 750);
> chart.trackSizes = 25;
> 
>  // manually set chart scale
> chart.scale.pretty = false; // turn off all auto scale features
> 
>  // set max and min
> chart.scale.max = 2210;
> chart.scale.min = 0;
> 
>  // chart.scale.font.size = 0;
> 
> // chart.tick.auto = true;
> 
>  //set colors
> chart.gene.text.color = "white";
> 
> // set reasonable tick marks
>  chart.tick.major.size = 0;
> chart.tick.minor.size = 0;
> 
> chart.gene.text.size = 10;
> 
>  // create a track
> 
> track = chart.addTrack();
> 
>  domain0 = track.addGene(1, 66, "+");
> domain0.name ="NTS-B2";
> 
>  if ("NTS-B2".match(/dbl/i)){
> 
> domain0.color = "green";
> domain0.roundness=10;
> }
> else if ("NTS-B2".match(/cidr/i)){
> domain0.color = "red";
> domain0.roundness=10;
>  }
> else if ("NTS-B2".match(/nts/i)){
> domain0.color = "blue";
> domain0.roundness=10;
>  }
> else {
> domain0.color = "purple";
> domain0.roundness=10;
> }
>  domain0.onMouseover = 'NTS-B2: start: 1 len: 66';
>  domain1 = track.addGene(68, 428, "+");
> domain1.name ="DBLα0.4";
>  if ("DBLα0.4".match(/dbl/i)){
> domain1.color = "green";
> domain1.roundness=10;
> }
> else if ("DBLα0.4".match(/cidr/i)){
> domain1.color = "red";
> domain1.roundness=10;
>  }
> else if ("DBLα0.4".match(/nts/i)){
> domain1.color = "blue";
> domain1.roundness=10;
>  }
> else {
> domain1.color = "purple";
> domain1.roundness=10;
> }
>  domain1.onMouseover = 'DBLα0.4: start: 68 len: 428';
>  domain2 = track.addGene(497, 298, "+");
> domain2.name ="cidrα3.1";
>  if ("cidrα3.1".match(/dbl/i)){
> domain2.color = "green";
> domain2.roundness=10;
> }
> else if ("cidrα3.1".match(/cidr/i)){
> domain2.color = "red";
> domain2.roundness=10;
>  }
> else if ("cidrα3.1".match(/nts/i)){
> domain2.color = "blue";
> domain2.roundness=10;
>  }
> else {
> domain2.color = "purple";
> domain2.roundness=10;
> }
>  domain2.onMouseover = 'cidrα3.1: start: 497 len: 298';
>  domain3 = track.addGene(870, 497, "+");
> domain3.name ="dblδ1";
>  if ("dblδ1".match(/dbl/i)){
> domain3.color = "green";
> domain3.roundness=10;
> }
> else if ("dblδ1".match(/cidr/i)){
> domain3.color = "red";
> domain3.roundness=10;
>  }
> else if ("dblδ1".match(/nts/i)){
> domain3.color = "blue";
> domain3.roundness=10;
>  }
> else {
> domain3.color = "purple";
> domain3.roundness=10;
> }
>  domain3.onMouseover = 'dblδ1: start: 870 len: 497';
>  domain4 = track.addGene(1368, 260, "+");
> domain4.name ="cidrβ5";
>  if ("cidrβ5".match(/dbl/i)){
> domain4.color = "green";
> domain4.roundness=10;
> }
> else if ("cidrβ5".match(/cidr/i)){
> domain4.color = "red";
> domain4.roundness=10;
>  }
> else if ("cidrβ5".match(/nts/i)){
> domain4.color = "blue";
> domain4.roundness=10;
>  }
> else {
> domain4.color = "purple";
> domain4.roundness=10;
> }
>  domain4.onMouseover = 'cidrβ5: start: 1368 len: 260';
>  domain5 = track.addGene(1745, 465, "+");
> domain5.name ="ATS-B6";
>  if ("ATS-B6".match(/dbl/i)){
> domain5.color = "green";
> domain5.roundness=10;
> }
> else if ("ATS-B6".match(/cidr/i)){
> domain5.color = "red";
> domain5.roundness=10;
>  }
> else if ("ATS-B6".match(/nts/i)){
> domain5.color = "blue";
> domain5.roundness=10;
>  }
> 
> else {
> domain5.color = "purple";
> domain5.roundness=10;
> }
> 
>  domain5.onMouseover = 'ATS-B6: start: 1745 len: 465';
> ;
> 
>  // draw the chart
> chart.draw();
> }
> 
> On Thu, Apr 7, 2011 at 8:29 PM, chmille4 <
> reply@reply.github.com>wrote:
> 
> > I'm not sure if you get a notification when I comment on the issue you
> > opened so I'll just send you an email as well.
> > 
> > I'm having trouble reproducing the bug you describe.  Can you send me some
> > code that displays this issue?
> > 
> > Thanks,
> > Chase
> > 
> > On Thu, Apr 7, 2011 at 1:07 PM, georgeG <
> > reply@reply.github.com>wrote:
> > 
> > > Glyph color is black by default,
> > > hover the mouse on the canvas to reset color to what is specified in the
> > > code
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/chmille4/Scribl/issues/11
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/chmille4/Scribl/issues/11#comment_969957
> 
> ## 
> 
> ---
> 
> Sincerely
> George
> KEMRI/Wellcome-Trust Research Program
> Skype: george_g2
> Blog: http://biorelated.wordpress.com/

## 

---

Sincerely
George
KEMRI/Wellcome-Trust Research Program
Skype: george_g2
Blog: http://biorelated.wordpress.com/

**Comment by ghost** [comment]
Hi  Chase,
Am using Rails3 and erb template to generate the resulting javascript. So
when i load the page, the glyph name is in black, and the text font is about
12. Upon hovering the mouse on the canvas object. The correct textcolor
(white) as specified in the code.

 function draw(canvasName) {
// Get Canvas and Create Chart
canvas = document.getElementById(canvasName);

 // create a canvas chart
chart = new Scribl(canvas, 750);
chart.trackSizes = 25;

 // manually set chart scale
chart.scale.pretty = false; // turn off all auto scale features

 // set max and min
chart.scale.max = 2210;
chart.scale.min = 0;

 // chart.scale.font.size = 0;

// chart.tick.auto = true;

 //set colors
chart.gene.text.color = "white";

// set reasonable tick marks
 chart.tick.major.size = 0;
chart.tick.minor.size = 0;

chart.gene.text.size = 10;

 // create a track

track = chart.addTrack();

 domain0 = track.addGene(1, 66, "+");
domain0.name ="NTS-B2";

 if ("NTS-B2".match(/dbl/i)){

domain0.color = "green";
domain0.roundness=10;
}
else if ("NTS-B2".match(/cidr/i)){
domain0.color = "red";
domain0.roundness=10;
 }
else if ("NTS-B2".match(/nts/i)){
domain0.color = "blue";
domain0.roundness=10;
 }
else {
domain0.color = "purple";
domain0.roundness=10;
}
 domain0.onMouseover = 'NTS-B2: start: 1 len: 66';
 domain1 = track.addGene(68, 428, "+");
domain1.name ="DBLα0.4";
 if ("DBLα0.4".match(/dbl/i)){
domain1.color = "green";
domain1.roundness=10;
}
else if ("DBLα0.4".match(/cidr/i)){
domain1.color = "red";
domain1.roundness=10;
 }
else if ("DBLα0.4".match(/nts/i)){
domain1.color = "blue";
domain1.roundness=10;
 }
else {
domain1.color = "purple";
domain1.roundness=10;
}
 domain1.onMouseover = 'DBLα0.4: start: 68 len: 428';
 domain2 = track.addGene(497, 298, "+");
domain2.name ="cidrα3.1";
 if ("cidrα3.1".match(/dbl/i)){
domain2.color = "green";
domain2.roundness=10;
}
else if ("cidrα3.1".match(/cidr/i)){
domain2.color = "red";
domain2.roundness=10;
 }
else if ("cidrα3.1".match(/nts/i)){
domain2.color = "blue";
domain2.roundness=10;
 }
else {
domain2.color = "purple";
domain2.roundness=10;
}
 domain2.onMouseover = 'cidrα3.1: start: 497 len: 298';
 domain3 = track.addGene(870, 497, "+");
domain3.name ="dblδ1";
 if ("dblδ1".match(/dbl/i)){
domain3.color = "green";
domain3.roundness=10;
}
else if ("dblδ1".match(/cidr/i)){
domain3.color = "red";
domain3.roundness=10;
 }
else if ("dblδ1".match(/nts/i)){
domain3.color = "blue";
domain3.roundness=10;
 }
else {
domain3.color = "purple";
domain3.roundness=10;
}
 domain3.onMouseover = 'dblδ1: start: 870 len: 497';
 domain4 = track.addGene(1368, 260, "+");
domain4.name ="cidrβ5";
 if ("cidrβ5".match(/dbl/i)){
domain4.color = "green";
domain4.roundness=10;
}
else if ("cidrβ5".match(/cidr/i)){
domain4.color = "red";
domain4.roundness=10;
 }
else if ("cidrβ5".match(/nts/i)){
domain4.color = "blue";
domain4.roundness=10;
 }
else {
domain4.color = "purple";
domain4.roundness=10;
}
 domain4.onMouseover = 'cidrβ5: start: 1368 len: 260';
 domain5 = track.addGene(1745, 465, "+");
domain5.name ="ATS-B6";
 if ("ATS-B6".match(/dbl/i)){
domain5.color = "green";
domain5.roundness=10;
}
else if ("ATS-B6".match(/cidr/i)){
domain5.color = "red";
domain5.roundness=10;
 }
else if ("ATS-B6".match(/nts/i)){
domain5.color = "blue";
domain5.roundness=10;
 }

else {
domain5.color = "purple";
domain5.roundness=10;
}

 domain5.onMouseover = 'ATS-B6: start: 1745 len: 465';
;

 // draw the chart
chart.draw();
}

On Thu, Apr 7, 2011 at 8:29 PM, chmille4 <
reply@reply.github.com>wrote:

> I'm not sure if you get a notification when I comment on the issue you
> opened so I'll just send you an email as well.
> 
> I'm having trouble reproducing the bug you describe.  Can you send me some
> code that displays this issue?
> 
> Thanks,
> Chase
> 
> On Thu, Apr 7, 2011 at 1:07 PM, georgeG <
> reply@reply.github.com>wrote:
> 
> > Glyph color is black by default,
> > hover the mouse on the canvas to reset color to what is specified in the
> > code
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/chmille4/Scribl/issues/11
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chmille4/Scribl/issues/11#comment_969957

## 

---

Sincerely
George
KEMRI/Wellcome-Trust Research Program
Skype: george_g2
Blog: http://biorelated.wordpress.com/

**Comment by chmille4** [comment]
Ok, I see the bug. I'll fix it.

**Comment by chmille4** [comment]
Fixed in version 0.2.1 https://github.com/chmille4/Scribl/tree/v0.2.1

Thanks George!

**Comment by ghost** [comment]
Thanks great!
