### ISSUE TITLE
color setting and font resizing when using track.addProtein helper method

### ISSUE THREAD

**Issue by ghost** [chmille4/Scribl#12]
text color and text font resizing does not work when using using the track.addProtein helper method

**Comment by chmille4** [comment]
can you paste me the js code?

Are you talking about changing the text color of the chart or of a particular protein:

<pre><code>
// whole chart 
chart.protein.text.color = "white"
chart.protein.text.font = "arial"
 
// individual protein
var protein1 = track.addProtein...
protein1.font.color = "white";
protein1.font.style = "arial";
</code></pre>


I know the api is inconsistent here and it's something I need to fix.

**Comment by ghost** [comment]
fixed it by declaring it at the whole chart level. Actually it might not be an issue. my inconsistency rather.
