### ISSUE TITLE
Enable placement of scale in arbitrary vertical position?

### ISSUE THREAD

**Issue by wwood** [chmille4/Scribl#22]
Hi,

Thanks for writing and continuing to work on Scribl. It is very useful, and seems to be a good fit for a replacement for wwwblast that we are writing, called [SequenceServer](http://www.sequenceserver.com/). There's a (very early) example of how we are using Scribl here:
http://www.flickr.com/photos/48558892@N07/6130431662/in/photostream/lightbox/

One thing were wondering is if it might be possible to position the scale bar in the middle of the canvas, so that some tracks are displayed above, and some below. I wasn't able to find that in the Scribl documentation - is it supported?

Thanks,
ben

**Comment by chmille4** [comment]
Hi Ben

I'm glad you are finding Scribl useful.

At the moment Scribl does not support changing the position of the
scale, but it shouldnt be too hard to add.  Off the top of my head, I
can think of two ways two do this.

(1) Add an an attribute to the scale that would cause it to be
displayed in the middle (e.g. chart.scale.position = 'middle'). This
would be easy to implement and would allow placement at the top,
bottom, or middle, but not fine control.

(2) Allow fine control by treating the scale as a track (e.g. var
scale = chart.addScaleTrack(); ). This would allow the user to place
the scale (or even multiple scales) wherever they like. However, it is
a bit complex and might be overkill.

If you don't need fine control and option (1) fits your needs, I think
that would be the way to go at the moment.  What do you think?

I'm out of the country at the moment, but I should be able to add
support for this by Wednesday.

I'm trying to compile a list of places Scribl is being used. Are you
currently using Scribl in SequenceServer? Or just experimenting?

Also, I just checked out SequenceServer (or the best I could on my
phone) and it looks very nice. I like the focus on user friendliness -
something a lot of bioinformatics projects gets wrong.

Cheers,
Chase

Sent from my iPhone

On Sep 9, 2011, at 10:12 PM, Ben J Woodcroft
reply@reply.github.com
wrote:

**Comment by wwood** [comment]
Thanks for the reply. I've implemented a prototype in a git branch but it hasn't made it into the master yet. We are still deciding on a spec for the graphical overview of the blast hits. At this point then I was just asking if the feature existed. I don't wish to make work for you or the project.

Are you suggesting that number 2 option would be difficult to implement?

**Comment by chmille4** [comment]
Hi Ben, sorry for the delayed response; I've been traveling with limited
access to internet.

At this point then I was just asking if the feature existed. I don't wish to

> make work for you or the project.

I really appreciate feature requests, especially when the feature could have
use for lots of people. I think having more control over the scale is
something that should be added, so its worth it to spend a little time on
it.

> Are you suggesting that number 2 option would be difficult to implement?

It's not too difficult to implement, but I worry how to nicely fit it into
the API and the internals (e.g. how to keep a default scale, but allow the
scale to be turned off to add a scale in other locations).  I'll have to
give it a think. Does this option better fit what you are trying to do?

Cheers,
Chase

**Comment by wwood** [comment]
> Hi Ben, sorry for the delayed response; I've been traveling with limited access to internet.

No worries, totally understand.

> I really appreciate feature requests, especially when the feature could have use for lots of people. I think having more control over the scale is something that should be added, so its worth it to spend a little time on it.

Great. So, you wouldn't mind me contributing another one then? It would be useful for us to be able to have variable height lanes (so good hits in the BLAST result have bigger lanes)..

> > Are you suggesting that number 2 option would be difficult to implement?
> 
> It's not too difficult to implement, but I worry how to nicely fit it into the API and the internals (e.g. how to keep a default scale, but allow the scale to be turned off to add a scale in other locations). I'll have to give it a think. Does this option better fit what you are trying to do?

I think number 2 is the go, because come to think of it, we won't always want it in the middle. Being able to say "put a gene here, then another gene, then put a scale here, then another gene" is what we are after.

Thanks,
ben

**Comment by chmille4** [comment]
> Great. So, you wouldn't mind me contributing another one then? It would be useful for us to be able to have variable height  lanes (so good hits in the BLAST result have bigger lanes)..

Of course, ask away!

This can be done currently (though its not clear from the usage guide or API), by doing `lane.height = 30; // in pixels`.  However you may not be dealing with lanes directly so for example if you wanted to make each lane size proportional to the number of genes that are on that lane you could use something like the code below

``` javascript
// determine the most # of features on any lane
chart.laneSizes = 50;
var maxFeatures = 0;
for ( var i=0; i<chart.tracks.length; i++) {
   for ( var j=0; j<chart.tracks[i].lanes.length; j++ ) {
      var numFeatures = chart.tracks[i].lanes[j].features.length;
      if (maxFeatures < numFeatures) 
         maxFeatures = numFeatures;
      }
   }

// deterimine lane heights based on number of features it contains
// normalized so that the lane with the most features will be 100% of set laneSize
// and the rest a % of the set laneSize
for ( var i=0; i<chart.tracks.length; i++) {
   for ( var j=0; j<chart.tracks[i].lanes.length; j++ ) {
      var numFeatures = chart.tracks[i].lanes[j].features.length;
      chart.tracks[i].lanes[j].height = chart.laneSizes * (numFeatures / maxFeatures);
   }
}

```

> I think number 2 is the go, because come to think of it, we won't always want it in the middle. Being able to say "put a gene here, then another gene, then put a scale here, then another gene" is what we are after.

This is probably better in the long run. I'll go ahead and try to figure out how to do this without adding too much complexity to the API.

**Comment by chmille4** [comment]
I've updated the usage guide to show how to change lane sizes in case other people stumble across this.

https://github.com/chmille4/Scribl/wiki/v1.0#wiki-lane_size_and_buffers

**Comment by wwood** [comment]
Cool, perfect.

**Comment by chmille4** [comment]
Ok, so I've added these changes and updated the version number to [v1.0.2](https://github.com/chmille4/Scribl/tree/v1.0.2). So grab that or do a git pull and give it a try.

You can see an example of usage [here](https://github.com/chmille4/Scribl/wiki/v1.0#wiki-change_scale_position)

I'm going to go ahead and close this, but let me know how it works for you.

Cheers

**Comment by wwood** [comment]
Fantastic. When I get a chance I'll try it out, and comment further if necessary.
