### ISSUE TITLE
Feature Request: Circular Tracks 

### ISSUE THREAD

**Issue by zachcp** [chmille4/Scribl#26]
Hi Chase,

I was thinking that it might be nice to have a circular mode for displaying circular DNA. I can imagine Scribl being used as a front end for a database of plasmid maps, for example.

thanks,
zach cp

**Comment by chmille4** [comment]
Hi Zach,

Interesting idea. I'd like to add some additional visual modes to scribl, opposed to just the alignment style display of data that it currently does. And this would be a good choice. I'll leave this open and try to incorporate it in the next major update.
